# 项目相关配置
lzj:
  # 名称
  name: ProjectFlowApplication
  # 版本
  version: 1.0-SNAPSHOT
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/lzj/uploadPath，Linux配置 /home/projectflow/uploadPath）
  profile: D:/lzj/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
  #服务器ip，许多环境都是在这上面 minio，mysql，redis 本地虚拟环境ip: 192.168.154.128 远程ip1:120.26.56.61  远程ip2: 47.100.54.116
  ip: 192.168.154.128
  # 对flowableui登录接口的一些配置
  flow:
    loginname: j_username
    loginpwd: j_password
    ip: localhost:8888
    cookies_prifix: FLOWABLE_REMEMBER_ME=
    loginapi: http://localhost:8888/app/authentication
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.lzj: debug
    org.springframework: warn
    org.activiti.engine.impl.persistence.entity: warn
# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  ai:
    openai:
      api-key: sk-qddoqfbcoawzgdvtcunezqzycfdqmxokcltnumagswgdzvcu
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-V2.5
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b  # 本地部署的大模型
  #activiti7配置
#  activiti:
#    check-process-definitions: false
#    database-schema-update: true
#    history-level: full
#    db-history-used: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
      enabled: true
  #解决activity7依赖冲突
  main:
    allow-bean-definition-overriding: true
  #flowable配置
#flowable:
#  idm:
#    app:
#      admin:
#        user-id: admin
#        password: admin
#        first-name: lzj
#        last-name: lzj
#  database-schema-update: true
#  async-executor-activate: false
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  #消息队列配置
  rabbitmq:
    host: 192.168.154.128
    username: admin
    password: admin
    virtual-host: test
    port: 5672
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
  #mybatis:
  # 搜索指定包别名
  #typeAliasesPackage: com.lzj.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  #mapperLocations: classpath*:com.lzj/**/mapper/*Mapper.xml
  # 加载全局的配置文件
  #configLocation: classpath:mybatis/mybatis-config.xml
  #MyBatis-Plus配置
mybatis-plus:
  type-aliases-package: com.lzj.**.domain
  mapper-locations: classpath*:com.lzj/**/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
page helper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
# oss对象存储配置
minio:
  # 访问地址
  endpoint: http://${lzj.ip}:9000
  # 用户名
  accessKey: admin
  # 密码
  secretKey: 12345678
  # 存储桶名称
  bucketName: 2024
  # 访问域名
  domain: http://${lzj.ip}:9000
#下载xml文件地址：http://localhost:8888/modeler-app/rest/models/994e2de7-9f67-11ef-aeb6-005056c00001/bpmn20
#http://localhost:8888/modeler/#/processes/994e2de7-9f67-11ef-aeb6-005056c00001
#http://localhost:8888/modeler/#/editor/0bbd5253-aa5a-11ef-9191-005056c00001

#Remove-Item -Recurse -Force node_modules 清除依赖
#npm cache clean --force  清除vue缓存
#--legacy-peer-deps 强制下载，不校验依赖是否匹配

