# 流程引擎环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8888
  servlet:
    # 应用的访问路径
    context-path: /
# 日志配置
logging:
  level:
    com.lzj: warn
    org.springframework: warn
#flowable配置
flowable:
  idm:
    app:
      admin:
        user-id: admin
        password: admin
        first-name: admin
        last-name: admin
  database-schema-update: true
  async-executor-activate: false
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b  # ????????
